import {CampusScene,ANCHORS} from './scene.js';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const DATA=await fetch('./capabilities.json').then(r=>{if(!r.ok)throw Error('Capability evidence could not be loaded');return r.json()}).catch(()=>null);
if(!DATA){$('#render-mode').textContent='Evidence unavailable. Please reload.';throw Error('Capability data unavailable')}
const byScope=Object.fromEntries(DATA.scopes.map(x=>[x.id,x]));
byScope.power={id:'power',label:'Power infrastructure',headline:'Connect generation, powerlines and substations',role:'self-perform',roleLabel:'Bird self-perform capability',documentedCapability:'Bird lists power generation, high- and medium-voltage powerlines, and substations within its integrated self-perform services.',boundary:'Infrastructure delivery does not establish power availability, grid connection rights, utility approvals or energy pricing. Confirm the project scope and delivery team.',sourceIds:['B1','B5','B6'],valueMechanisms:{schedule:'Bring generation, line and substation workfaces into a coordinated delivery sequence',cost:'Use direct trade input to define the interfaces between generation, network and receiving equipment',risk:'Make the utility boundary and the handover between power packages explicit',quality:'Connect direct workmanship accountability with package inspection and testing requirements',safety:'Plan adjacent power workfaces and access while retaining electrical isolation and authorization controls',coordination:'Connect the power infrastructure trades and the information they need from each other'}};
byScope.interface={id:'interface',label:'Civil to electrical interface',headline:'Connect the trades that depend on each other',role:'self-perform',roleLabel:'Connected self-perform capabilities',documentedCapability:'Bird publishes self-perform capability in underground utilities and electrical work. This assembly illustrates where those trades meet.',boundary:'This is an illustrative combined scope. Internal technical handovers, inspections and receiving-trade acceptance remain. The actual bundle and responsibilities need agreement.',sourceIds:['B1','B5','B8'],valueMechanisms:{...byScope.utilities.valueMechanisms}};
const chapterDefaults=['power','planning-design','utilities','electrical','interface','hv-testing','expansion'];
const primaryStages=['power','design-procure','below-grade','plant','plant','prove','expand'];
const stageShort=['Define','Permit','Power','Design','Civil','Utilities','Structure','M&E','White space','Prove','Operate','Expand'];
const scopeForStage=['planning-design','permit-authority','power','planning-design','earthworks','utilities','structure-enclosure','electrical','white-space','hv-testing','owner-acceptance','expansion'];
const kickers=['THE SELF-PERFORM ADVANTAGE','EARLY DELIVERY INSIGHT','DIRECT TRADE CAPABILITY','MISSION-CRITICAL SYSTEMS','BIRD CAPABILITY. CLIENT VALUE.','TESTING & ACCEPTANCE','LIFECYCLE CONTINUITY'];
const lensTitles={schedule:'Control over field sequencing',cost:'Earlier input from delivery teams',risk:'Make responsibility visible',quality:'Direct workmanship accountability',safety:'Coordinated workface planning',coordination:'Connected trades and information'};
const state={chapter:0,scope:'power',lens:'coordination',panelOpen:false,stage:'power',reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,mode:'loading'};
let labels=[],lastScopeOpener=null,lastScopeFocusId=null,scrollFrame=0,navigationUntil=0,lockedScroll=0;
const scene=new CampusScene($('#campus'),mode=>{state.mode=mode;$('#render-mode').textContent=mode},id=>selectScope(id,true));
scene.reduced=state.reducedMotion;
const sourceMap=Object.fromEntries(DATA.sources.map(s=>[s.id,s]));
function esc(t){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chapterIndex(id){const i=DATA.chapters.findIndex(c=>c.id===id);if(i<0)throw Error('Unknown chapter');return i}
function scopeIds(){const arr=[...DATA.chapters[state.chapter].scopeIds];if(state.chapter===0||state.chapter===1)arr.unshift('power');if(state.chapter===4)arr.unshift('interface');return arr}
function sync(){const ch=DATA.chapters[state.chapter],s=byScope[state.scope];$('#chapter-number').textContent=`${String(state.chapter+1).padStart(2,'0')} / 07`;$('#chapter-kicker').textContent=kickers[state.chapter];$('#chapter-title').textContent=ch.headline;$('#chapter-subtitle').textContent=ch.description;$('#active-label').textContent=s.label;$('#active-role').textContent=s.roleLabel;$('#step-count').textContent=`${String(state.chapter+1).padStart(2,'0')} / 07`;$('#prev-stage').disabled=state.chapter===0;$('#next-stage').disabled=state.chapter===6;$('#stage-boundary').textContent=state.chapter===0?'Seven connected views. Lifecycle workstreams overlap.':state.chapter===5?'HV package testing, commissioning support and owner acceptance are distinct.':state.chapter===6?'Owner operations and project maintenance scope remain separate.':'Grey = inactive scope. Colour does not establish project allocation.';
 $$('#chapter-rail button').forEach((b,i)=>b.setAttribute('aria-current',i===state.chapter?'step':'false'));$$('#lifecycle button').forEach(b=>b.setAttribute('aria-current',b.dataset.stage===state.stage?'step':'false'));
 $('#scope-list').innerHTML=scopeIds().map(id=>`<button type="button" data-scope="${id}" aria-pressed="${id===state.scope}">${esc(byScope[id].label)}</button>`).join('');
 scene.setState(state.chapter,state.scope,state.panelOpen);scene.selectable=scopeIds().filter(id=>ANCHORS[id]);updateLabels();updatePanel();$('#announcement').textContent=`${ch.label}. ${s.label}. ${s.roleLabel}.`;document.title=`Bird | ${ch.label} · From Site to Service`;
}
function setChapter(i,{scope,stage,announce=true}={}){if(!Number.isInteger(i)||i<0||i>6)throw Error('Chapter must be between 0 and 6');state.chapter=i;state.scope=scope||chapterDefaults[i];state.stage=stage||primaryStages[i];scene.reset();sync()}
function navigateChapter(i,options={}){if(i<0||i>6)return;if(state.panelOpen)closePanel(false);setChapter(i,options);navigationUntil=performance.now()+900;const y=i/6*(document.documentElement.scrollHeight-innerHeight);window.scrollTo({top:y,behavior:state.reducedMotion?'instant':'smooth'});history.replaceState(null,'',`#${DATA.chapters[i].id}`);return readState()}
function openPanel(){if(state.panelOpen)return;if(performance.now()<navigationUntil){window.scrollTo({top:state.chapter/6*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'});}state.panelOpen=true;lockedScroll=scrollY;document.body.classList.add('panel-open');document.body.style.overflow='hidden';$('#capability-panel').hidden=false;scene.setState(state.chapter,state.scope,true);updatePanel();$('#capability-close').focus({preventScroll:true})}
function closePanel(focus=true){state.panelOpen=false;document.body.classList.remove('panel-open');document.body.style.overflow='';$('#capability-panel').hidden=true;scene.setState(state.chapter,state.scope,false);window.scrollTo({top:lockedScroll,behavior:'instant'});if(focus){const replacement=lastScopeFocusId?$('#scope-list [data-scope="'+lastScopeFocusId+'"]'):null;const visibleDefault=$('#scope-list [data-scope="'+state.scope+'"]')||$('#capability-open');(lastScopeOpener?.isConnected?lastScopeOpener:replacement||visibleDefault).focus({preventScroll:true})}}
function selectScope(id,open=true){if(!byScope[id])throw Error('Unknown scope');if(!scopeIds().includes(id)){const s=byScope[id],ch=s.chapterIds?.[0]||'overview';navigateChapter(chapterIndex(ch));}state.scope=id;lastScopeOpener=document.activeElement;lastScopeFocusId=lastScopeOpener?.dataset?.scope||id;sync();if(open)openPanel();return readState()}
function setLens(id){if(!DATA.lenses.some(l=>l.id===id))throw Error('Unknown client lens');state.lens=id;updatePanel();return readState()}
function updatePanel(){const s=byScope[state.scope],lens=DATA.lenses.find(l=>l.id===state.lens);$('#detail-role').textContent=s.roleLabel;$('#detail-role').dataset.role=s.role;$('#detail-title').textContent=s.label;$('#detail-capability').textContent=s.documentedCapability;$('#detail-boundary').textContent=s.boundary;$('#lens-title').textContent=lensTitles[state.lens];$('#lens-copy').textContent=s.valueMechanisms[state.lens];$('.value-qualification').textContent=`${lens.qualification}. Potential value depends on agreed scope and project conditions.`;$$('#lens-tabs button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.lens===state.lens));const ids=[...new Set([...s.sourceIds,...DATA.mechanismEvidence[state.lens]])];$('#detail-sources').innerHTML='<span>Official Bird evidence</span>'+ids.map(id=>`<a target="_blank" rel="noopener noreferrer" href="${sourceMap[id].url}" title="${esc(sourceMap[id].title)}">${id}</a>`).join('')}
function updateLabels(){let ids;if(state.scope==='power')ids=['powerlines','substations','generation'];else if(state.scope==='interface')ids=['utilities','electrical','concrete'];else{ids=[state.scope,...scopeIds().filter(id=>id!==state.scope&&ANCHORS[id])].slice(0,3)}ids=ids.filter(id=>ANCHORS[id]);$('#spatial-labels').innerHTML=ids.map(id=>`<button class="spatial-label ${(id===state.scope||state.scope==='power'||state.scope==='interface'&&['utilities','electrical'].includes(id))?'active':''}" data-scope="${id}" aria-label="Explore ${esc(byScope[id].label)}"><span>${esc(byScope[id].label)}</span><i></i><b></b></button>`).join('');labels=ids.map(id=>({id,el:$('#spatial-labels [data-scope="'+id+'"]')}));scene.dirty=true}
scene.drawLabels=()=>{const mobile=scene.width<761;let used=[];for(const {id,el} of labels){const p=scene.project(ANCHORS[id]);let x=p.x,y=p.y;const width=el.offsetWidth||140;const clampedX=Math.max(width/2+10,Math.min(scene.width-width/2-15,x));const clampedY=Math.max(45,Math.min(scene.height-15,y));x=clampedX;y=clampedY;for(const q of used){if(Math.abs(q.x-x)<(q.w+width)/2+8&&Math.abs(q.y-y)<54)y-=55}used.push({x,y,w:width});el.style.left=`${x}px`;el.style.top=`${y}px`;el.style.opacity=p.x<-20||p.x>scene.width+20||p.y>scene.height+20||p.y<-50?'0':'1';el.style.pointerEvents=el.style.opacity==='0'?'none':'auto';if(!mobile&&state.panelOpen&&x>scene.width-435)el.style.visibility='hidden';else el.style.visibility='visible'}};
function readState(){const s=byScope[state.scope];return{chapter:DATA.chapters[state.chapter].id,stage:state.stage,scope:state.scope,scopeLabel:s.label,role:s.role,lens:state.lens,panelOpen:state.panelOpen,reducedMotion:state.reducedMotion,renderMode:state.mode,documentedCapability:s.documentedCapability,boundary:s.boundary,mechanism:s.valueMechanisms[state.lens],sources:s.sourceIds.map(id=>({id,url:sourceMap[id].url}))}}
$('#chapter-rail').innerHTML=DATA.chapters.map((c,i)=>`<button class="chapter-dot" data-chapter="${i}" aria-label="${i+1}. ${esc(c.label)}" title="${esc(c.label)}"><span>${String(i+1).padStart(2,'0')} ${esc(c.label)}</span><i></i></button>`).join('');
$('#lifecycle').innerHTML=DATA.stages.map((s,i)=>`<button data-stage="${s.id}" data-index="${i}" aria-label="${s.number}. ${esc(s.label)}" title="${esc(s.label)}"><i></i><span>${stageShort[i]}</span></button>`).join('');
$('#lens-tabs').innerHTML=DATA.lenses.map(l=>`<button type="button" data-lens="${l.id}" aria-pressed="${l.id===state.lens}">${l.label}</button>`).join('');
$('#source-register').innerHTML=DATA.sources.map(s=>`<li><a href="${s.url}" target="_blank" rel="noopener noreferrer"><span class="source-id">${s.id}</span>${esc(s.title)}</a><p>${esc(s.evidenceSummary)}</p><p class="muted">${esc(s.boundary)} ${esc(s.currency)}</p></li>`).join('');
$('#chapter-rail').addEventListener('click',e=>{const b=e.target.closest('[data-chapter]');if(b)navigateChapter(Number(b.dataset.chapter))});
$('#lifecycle').addEventListener('click',e=>{const b=e.target.closest('[data-stage]');if(!b)return;const n=Number(b.dataset.index),s=DATA.stages[n];navigateChapter(chapterIndex(s.chapterId),{stage:s.id,scope:scopeForStage[n]});b.scrollIntoView({block:'nearest',inline:'nearest',behavior:state.reducedMotion?'instant':'smooth'})});
for(const container of ['#scope-list','#spatial-labels'])$(container).addEventListener('click',e=>{const b=e.target.closest('[data-scope]');if(b)selectScope(b.dataset.scope)});
$('#lens-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-lens]');if(b)setLens(b.dataset.lens)});
$('#capability-open').addEventListener('click',()=>{lastScopeOpener=$('#capability-open');openPanel()});$('#capability-close').addEventListener('click',()=>closePanel());$('#prev-stage').addEventListener('click',()=>navigateChapter(state.chapter-1));$('#next-stage').addEventListener('click',()=>navigateChapter(state.chapter+1));$('#view-reset').addEventListener('click',()=>scene.reset());
$('#motion-toggle').addEventListener('click',()=>{state.reducedMotion=!state.reducedMotion;scene.reduced=state.reducedMotion;scene.dirty=true;syncMotion()});function syncMotion(){document.body.classList.toggle('reduced-motion',state.reducedMotion);$('#motion-toggle').setAttribute('aria-pressed',String(state.reducedMotion));$('#motion-toggle').setAttribute('aria-label',state.reducedMotion?'Enable smooth camera motion':'Reduce camera motion')}
const dialog=$('#sources-dialog');function openSources(){document.body.classList.add('dialog-open');dialog.showModal()}function closeSources(){dialog.close();document.body.classList.remove('dialog-open')}
$('#sources-open').addEventListener('click',openSources);$('#sources-footer').addEventListener('click',openSources);$('#sources-close').addEventListener('click',closeSources);dialog.addEventListener('close',()=>document.body.classList.remove('dialog-open'));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSources()}});
$('.brand').addEventListener('click',e=>{e.preventDefault();navigateChapter(0)});
window.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;if(state.panelOpen||dialog.open||performance.now()<navigationUntil)return;const max=document.documentElement.scrollHeight-innerHeight;const index=Math.max(0,Math.min(6,Math.floor((scrollY/max)*6+.5)));if(index!==state.chapter){setChapter(index);history.replaceState(null,'',`#${DATA.chapters[index].id}`)}})},{passive:true});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.panelOpen&&!dialog.open)closePanel();if(!state.panelOpen&&!dialog.open&&e.target.tagName!=='CANVAS'&&['PageDown','PageUp','Home','End'].includes(e.key)){e.preventDefault();navigateChapter(e.key==='Home'?0:e.key==='End'?6:state.chapter+(e.key==='PageDown'?1:-1))}});
window.addEventListener('resize',()=>{if(state.panelOpen)return;navigationUntil=performance.now()+300;window.scrollTo({top:state.chapter/6*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'})});
syncMotion();sync();const initial=DATA.chapters.findIndex(c=>c.id===location.hash.slice(1));if(initial>0)setTimeout(()=>navigateChapter(initial),100);
// Public page actions are also available to a supported browser agent. They use
// exactly the same validated actions and visible state as the page controls.
const lifecycle=new AbortController();const context=document.modelContext;
if(context?.registerTool){const tools=[{name:'read_bird_journey',title:'Read Bird journey',description:'Read the currently visible chapter, capability, client lens and supporting evidence',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input&&Object.keys(input).length)throw Error('No fields expected');return readState()}},{name:'navigate_bird_chapter',title:'Navigate Bird chapter',description:'Navigate to one of the seven campus chapters. Does not change project data.',inputSchema:{type:'object',properties:{chapter:{type:'string',enum:DATA.chapters.map(c=>c.id)}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||Object.keys(input).some(k=>k!=='chapter'))throw Error('Supply only chapter');const result=navigateChapter(chapterIndex(input.chapter));await new Promise(requestAnimationFrame);return result}},{name:'explore_bird_capability',title:'Explore Bird capability',description:'Select a documented capability and an optional client lens, opening its evidence panel',inputSchema:{type:'object',properties:{scope:{type:'string',enum:Object.keys(byScope)},lens:{type:'string',enum:DATA.lenses.map(l=>l.id)}},required:['scope'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||Object.keys(input).some(k=>!['scope','lens'].includes(k))||!byScope[input.scope]||input.lens&&!DATA.lenses.some(l=>l.id===input.lens))throw Error('Supply a valid scope and optional lens');selectScope(input.scope);if(input.lens)setLens(input.lens);await new Promise(requestAnimationFrame);return readState()}}];for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
// A small non-mutating state read-back supports permitted QA and accessibility.
window.BirdJourney={getState:readState,modelStats:()=>({objects:scene.objects.length,faces:scene.objects.reduce((n,o)=>n+o.faces.length,0),renderer:scene.mode,chapters:DATA.chapters.length,stages:DATA.stages.length,scopes:DATA.scopes.length})};
