/* A single real 3D campus model. WebGL and the software renderer consume the
   same world-space vertices, face normals, role groups and camera state. */
export const CAMERAS=[
 {target:[-1,0,1],yaw:-.78,pitch:.62,span:145},
 {target:[4,0,0],yaw:-.78,pitch:.73,span:132},
 {target:[-1,-1,14],yaw:-.83,pitch:.38,span:77},
 {target:[15,3,-5],yaw:-.78,pitch:.63,span:90},
 {target:[1,1,10],yaw:-.78,pitch:.39,span:65},
 {target:[-26,3,10],yaw:-.70,pitch:.39,span:66},
 {target:[12,0,8],yaw:-.82,pitch:.65,span:142}
];
export const ANCHORS={generation:[-6,5,26],powerlines:[-53,14,8],substations:[-30,5,5],telecom:[31,5,-8],'thermal-transfer':[36,4,10],earthworks:[-7,-1,10],utilities:[1,-1,17],concrete:[9,1,8],electrical:[3,5,-7],mechanical:[27,6,-21],hvac:[14,9,-18],'white-space':[24,4,-6],'commissioning-support':[-18,4,8],'hv-testing':[-31,5,12],expansion:[38,1,25],maintenance:[39,3,0],'planning-design':[12,.5,-3],'permit-authority':[-7,1,-23],'structure-enclosure':[16,10,-6],'owner-acceptance':[5,2,29]};
const V=(x,y,z)=>[x,y,z],add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,n)=>a.map(v=>v*n),dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>mul(a,1/(Math.hypot(...a)||1));
const C={green:'#00703c',steel:'#819590',metal:'#bfc9c5',copper:'#be7d40',soil:'#a69072',sand:'#d4c5aa',concrete:'#bdc6bd',orange:'#ef8a32',black:'#354b41',white:'#dce4df',pipe:'#397e65',glass:'#659291',blue:'#60949d'};
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255)}
export function buildCampus(){
 const objects=[];let n=0;
 const face=(pts)=>({pts,normal:norm(cross(sub(pts[1],pts[0]),sub(pts[2],pts[0]))) });
 function mesh(scope,faces,color,options={}){const parts=[];for(const p of faces){if(p.length===4&&!options.terrain&&!options.flat&&!options.shadow){const a=sub(p[1],p[0]),b=sub(p[3],p[0]),nx=Math.ceil(Math.hypot(...a)/5),ny=Math.ceil(Math.hypot(...b)/5);if(nx>1||ny>1){for(let i=0;i<nx;i++)for(let j=0;j<ny;j++){const at=(u,v)=>add(p[0],add(mul(a,u/nx),mul(b,v/ny)));parts.push(face([at(i,j),at(i+1,j),at(i+1,j+1),at(i,j+1)]));}continue;}}parts.push(face(p))}objects.push({id:n++,scope,faces:parts,center:faces[0].reduce((a,p)=>add(a,mul(p,1/faces[0].length)),[0,0,0]),color:rgb(color||C.concrete),...options});}
 function box(scope,x,y,z,w,h,d,col,options={}){const p=[V(x-w/2,y,z-d/2),V(x+w/2,y,z-d/2),V(x+w/2,y+h,z-d/2),V(x-w/2,y+h,z-d/2),V(x-w/2,y,z+d/2),V(x+w/2,y,z+d/2),V(x+w/2,y+h,z+d/2),V(x-w/2,y+h,z+d/2)];if(options.angle){const a=options.angle;for(const q of p){const X=q[0]-x,Z=q[2]-z;q[0]=x+X*Math.cos(a)-Z*Math.sin(a);q[2]=z+X*Math.sin(a)+Z*Math.cos(a)}}mesh(scope,[[3,2,1,0],[4,5,6,7],[0,4,7,3],[2,6,5,1],[7,6,2,3],[0,1,5,4]].map(f=>f.map(i=>p[i])),col,options)}
 function pipe(scope,a,b,r,col,options={}){const axis=norm(sub(b,a)),u=norm(cross(axis,Math.abs(axis[1])>.9?[1,0,0]:[0,1,0])),v=cross(axis,u),N=options.sides||8,pa=[],pb=[];for(let i=0;i<N;i++){const q=add(mul(u,Math.cos(i/N*2*Math.PI)*r),mul(v,Math.sin(i/N*2*Math.PI)*r));pa.push(add(a,q));pb.push(add(b,q))}let faces=[pa.slice().reverse(),pb];for(let i=0;i<N;i++){const j=(i+1)%N;faces.push([pa[i],pa[j],pb[j],pb[i]])}mesh(scope,faces,col,options)}
 function route(scope,pts,r,col,opt={}){for(let i=0;i<pts.length-1;i++)pipe(scope,pts[i],pts[i+1],r,col,opt)}
 function frame(scope,x,z,w,d,h,col,opt={}){for(const X of [x-w/2,x+w/2])for(const Z of [z-d/2,z+d/2])box(scope,X,0,Z,.19,h,.19,col,opt);for(const Z of [z-d/2,z+d/2])box(scope,x,h,Z,w,.18,.18,col,opt);for(const X of [x-w/2,x+w/2])box(scope,X,h,z,.18,.18,d,col,opt)}
 function shadow(x,z,w,d,op=.10){box('context',x,-.025,z,w,.006,d,'#687b6b',{shadow:true,opacity:op})}
 // Terrain, road loop, cut soil edge and restrained cadastral grid.
 box('context',0,-3.9,0,123,.8,85,'#cbd1ca',{terrain:true});
 box('context',0,-3.1,-15.85,123,3.05,53.3,'#e4e9e2',{terrain:true});
 box('context',0,-3.1,29.75,123,3.05,25.5,'#e4e9e2',{terrain:true});
 box('context',-49.75,-3.1,13.9,23.5,3.05,6.2,'#e4e9e2',{terrain:true});
 box('context',39.75,-3.1,13.9,43.5,3.05,6.2,'#e4e9e2',{terrain:true});
 for(let x=-60;x<=60;x+=8)box('context',x,-.028,0,.025,.008,83,'#c9d1c9',{flat:true});for(let z=-40;z<=40;z+=8)box('context',0,-.029,z,121,.008,.025,'#c9d1c9',{flat:true});
 for(const z of [-31,35])box('context',0,0,z,117,.08,4,'#c1c9c3',{flat:true});for(const x of [-44,49])box('context',x,0,2,4,.08,64,'#c1c9c3',{flat:true});box('context',0,0,17,92,.06,4,'#c2ccc5',{flat:true});
 for(let x=-55;x<58;x+=4){box('context',x,.10,35,1.7,.01,.10,'#eff2ed',{flat:true});box('context',x,.10,-31,1.7,.01,.10,'#eff2ed',{flat:true})}
 // Main hall: 44 x 32 metres in this illustrative spatial model.
 shadow(15,-6,49,37,.13);box('concrete',15,0,-6,44,.55,32,C.concrete,{build:2});
 const hall={build:3};box('structure-enclosure',15,.55,-22,44,9,.3,C.white,{...hall,wall:true});box('structure-enclosure',37,.55,-6,.3,9,32,C.white,{...hall,wall:true});box('structure-enclosure',-7,.55,-6,.3,9,32,C.white,{...hall,wall:true,cut:true});box('structure-enclosure',15,.55,10,44,9,.3,C.white,{...hall,wall:true,cut:true});
 for(let x=-7;x<=37;x+=5.5){for(const z of [-22,10]){box('structure-enclosure',x,.55,z,.20,9.15,.34,C.steel,hall);box('structure-enclosure',x,9.45,-6,.19,.23,32,C.steel,hall)}}
 for(let z=-22;z<=10;z+=4)box('structure-enclosure',15,9.52,z,44,.20,.14,C.steel,hall);
 box('structure-enclosure',15,9.67,-6,44,.20,32,C.white,{...hall,roof:true});for(let x=-5;x<37;x+=2.2)box('structure-enclosure',x,9.9,-6,.035,.03,32,C.steel,{...hall,roof:true});
 // Interior zone separation. Low upstands remain visible through cutaway.
 box('concrete',10,.55,-6,.25,1,32,C.concrete,{build:2});box('concrete',23,.55,-6,.25,1,32,C.concrete,{build:2});
 for(let x=-5;x<9;x+=2.4){box('concrete',x,.55,8,1.5,.4,1.5,C.concrete,{build:2});box('concrete',x,.55,-20,1.5,.4,1.5,C.concrete,{build:2})}
 // Switchgear, UPS and electrical routing.
 for(let z=-18;z<=5;z+=4){for(const x of [-3,5]){box('electrical',x,.6,z,2.1,3.4,2.65,C.green,{build:3});box('electrical',x,.7,z+1.34,1.85,3.1,.03,C.metal,{build:3});box('electrical',x,2.45,z+1.37,.50,.46,.05,C.black,{build:3});box('electrical',x-.76,1.55,z+1.40,.09,.65,.04,C.black,{build:3});for(let l=0;l<5;l++)box('electrical',x-1.064,.97+l*.30,z,.035,.05,2.25,C.steel,{build:3});box('electrical',x-1.09,2.5,z,.04,.45,.55,C.black,{build:3});for(let l=0;l<3;l++)box('electrical',x+.54,.85+l*.18,z+1.39,.55,.05,.04,C.steel,{build:3});box('electrical',x+.65,3.45,z+1.41,.19,.20,.02,C.orange,{build:3})}}
 for(const x of [-3,5]){box('electrical',x,5.1,-6,1.2,.18,29,C.steel,{build:3});for(let k=0;k<4;k++)route('electrical',[[x-.42+k*.25,5.35,-20],[x-.42+k*.25,5.35,9],[x-.42+k*.25,.5,9],[x-.42+k*.25,-1.7,15]],.085,k===0?C.green:C.copper,{build:3});for(let z=-19;z<10;z+=3)box('electrical',x,5.09,z,1.5,.12,.08,C.metal,{build:3})}
 // Server halls and overhead telecom containment.
 for(let x=15;x<=33;x+=4.5)for(let z=-16;z<=5;z+=3){box('white-space',x,.58,z,1.25,2.9,2.1,C.black,{build:3});box('white-space',x-.65,.83,z,.03,2.3,1.8,C.steel,{build:3});for(let k=0;k<5;k++)box('white-space',x-.674,1.1+k*.42,z,.018,.08,1.62,C.metal,{build:3})}
 for(const x of [15,24,33]){box('telecom',x,4.45,-6,.60,.18,29,C.green,{build:3});for(let z=-18;z<=7;z+=5)box('telecom',x,3.45,z,.1,1,.1,C.copper,{build:3})}box('telecom',24,4.45,8,20,.18,.6,C.green,{build:3});
 // Mechanical plant and thermal transfer corridor.
 for(let i=0;i<5;i++){const x=9+i*5.2;box('mechanical',x,.15,-26.5,3.4,.3,4.2,C.concrete,{build:3});box('mechanical',x,.45,-26.5,2.8,3.2,3.8,C.green,{build:3});pipe('mechanical',[x,3.7,-27.8],[x,3.7,-25.2],.9,C.metal,{build:3});box('mechanical',x+.1,1.2,-24.55,1.2,1,.1,C.steel,{build:3})}
 for(let i=0;i<2;i++){const x=39+i*1.6;route('thermal-transfer',[[x,.7,26],[x,4.4,26],[x,4.4,-27],[30,4.4,-27]],.30,i?C.copper:C.green,{build:3});for(let z=-25;z<28;z+=5){box('thermal-transfer',x,.1,z,.2,4.3,.2,C.steel,{build:3});pipe('thermal-transfer',[x,4.4,z-.12],[x,4.4,z+.12],.41,C.metal,{build:3})}}
 // Rooftop HVAC; exposed in later cutaways as an offset service band.
 for(let x=0;x<=31;x+=6.2)for(const z of [-17,4]){box('hvac',x,9.95,z,3.8,1.1,3.4,C.green,{build:3,hvac:true});for(const X of [x-.9,x+.9]){pipe('hvac',[X,11.07,z],[X,11.19,z],.75,C.black,{build:3,hvac:true,sides:12});pipe('hvac',[X,11.20,z],[X,11.24,z],.56,C.steel,{build:3,hvac:true,sides:12});box('hvac',X,11.26,z,1.2,.015,.055,C.metal,{build:3,hvac:true});box('hvac',X,11.26,z,.055,.015,1.2,C.metal,{build:3,hvac:true})}}
 // Substation. Ground grid, transformers, insulators, busbars and gantries.
 shadow(-28,4,26,22,.1);box('substations',-28,.08,4,25,.18,22,C.sand,{build:2});
 for(let x=-39;x<=-17;x+=5.5){for(const z of [-6,14]){pipe('substations',[x,.25,z],[x,7.2,z],.14,C.steel,{build:3});pipe('substations',[x,7.2,z],[x,7.2,z+3],.09,C.steel,{build:3})}}
 for(let row=0;row<2;row++)for(let j=0;j<3;j++){const x=-35+j*7,z=-1+row*10;box('substations',x,.3,z,4.8,.5,4.5,C.concrete,{build:2});box('substations',x,.8,z,3.1,2.8,2.8,C.green,{build:3});for(let k=0;k<8;k++)box('substations',x-1.68,.98,z-1.3+k*.36,.2,2.0,.10,C.metal,{build:3});for(let k=-1;k<=1;k++){pipe('substations',[x+k,3.6,z],[x+k,5.6,z],.18,C.black,{build:3});for(let l=0;l<5;l++)pipe('substations',[x+k,4.1+l*.27,z],[x+k,4.16+l*.27,z],.30,C.metal,{build:3});route('substations',[[x+k,5.65,z],[x+k,6.0,z-3],[x+k,6.0,-7]],.095,C.copper,{build:3})}}
 for(const z of [-7,16])box('substations',-28,.15,z,27,2,.08,C.steel,{build:3,fence:true});for(const x of [-41,-15])box('substations',x,.15,4,.08,2,24,C.steel,{build:3,fence:true});
 for(let x=-41;x<=-15;x+=2){pipe('substations',[x,.2,16],[x,2.3,16],.04,C.steel,{build:3});pipe('substations',[x,.2,-8],[x,2.3,-8],.04,C.steel,{build:3})}
 // Generation yard.
 shadow(-6,26,24,13,.1);box('generation',-6,.1,26,24,.25,12,C.concrete,{build:2});for(let j=0;j<4;j++){const x=-14+j*5.2;box('generation',x,.4,26,3.5,3.1,7,C.green,{build:3});for(let k=0;k<7;k++)box('generation',x-1.77,.9+k*.27,25,.03,.09,3.9,C.black,{build:3});pipe('generation',[x,3.5,28],[x,7.2,28],.23,C.metal,{build:3});pipe('generation',[x+.65,3.5,28],[x+.65,6.4,28],.18,C.metal,{build:3});box('generation',x,2,29.55,1.4,.55,.03,C.black,{build:3});box('generation',x+1.2,.6,29.7,.25,1.4,.07,C.orange,{build:3})}
 // High/medium-voltage lattice towers and curved span conductors.
 for(const z of [-18,9,34]){const x=-53;for(const dx of [-1.5,1.5])for(const dz of [-1.5,1.5])pipe('powerlines',[x+dx,.1,z+dz],[x+dx*.2,17,z+dz*.2],.1,C.steel,{build:3});for(let y=2;y<16;y+=3){const r=1.5-y*.07;for(const s of [-1,1]){pipe('powerlines',[x-r,y,z+s*r],[x+r*.83,y+2.9,z+s*r*.83],.05,C.steel,{build:3});pipe('powerlines',[x+r,y,z+s*r],[x-r*.83,y+2.9,z+s*r*.83],.05,C.steel,{build:3})}}pipe('powerlines',[x-4,13,z],[x+4,13,z],.15,C.green,{build:3});pipe('powerlines',[x-3,16,z],[x+3,16,z],.12,C.green,{build:3});for(const dx of [-3.8,3.8])pipe('powerlines',[x+dx,13,z],[x+dx,11.7,z],.14,C.black,{build:3})}
 for(const x of [-56.8,-49.2])for(const interval of [[-18,9],[9,34]]){const p=[];for(let j=0;j<=12;j++){const t=j/12;p.push([x,11.7-Math.sin(t*Math.PI)*2.2,interval[0]+t*(interval[1]-interval[0])])}route('powerlines',p,.047,C.green,{build:3})}
 // Below-ground trench: a deliberate cutaway across the front of the hall.
 box('earthworks',-10,-3.05,13.9,56,3.0,6.2,C.soil,{trench:true});box('earthworks',0,-2.8,14.1,33,.2,5.7,C.sand,{build:2});for(const z of [11.35,16.85])box('concrete',0,-2.8,z,33,2.8,.18,C.concrete,{build:2,trenchWall:z>14});
 for(let i=0;i<4;i++){const z=12.1+i*1.12;route('utilities',[[-34,-1.7,z],[-2,-1.7,z],[5,-1.7,z],[5,-1.7,9],[5,.6,9]],i<2?.29:.17,i<2?C.green:C.black,{build:2});for(let x=-30;x<=0;x+=5)pipe('utilities',[x-.12,-1.7,z],[x+.12,-1.7,z],i<2?.37:.23,C.metal,{build:2})}
 for(let x=-13;x<=12;x+=5){box('concrete',x,-2.6,14, .32,.35,5,C.concrete,{build:2});for(const z of [11.5,16.65])box('concrete',x,-2.55,z,.16,2.7,.16,C.steel,{build:2})}
 // Planning footprint and off-site fabrication / logistics modules.
 for(const z of [-22,10])box('planning-design',15,.65,z,44,.035,.16,C.green,{planning:true});for(const x of [-7,37])box('planning-design',x,.65,-6,.16,.035,32,C.green,{planning:true});
 for(let i=0;i<3;i++){box('planning-design',-18+i*5,.12,-22,4,2.2,3.2,C.green,{planning:true});box('planning-design',-18+i*5,.5,-20.38,3.3,1.2,.04,C.glass,{planning:true})}
 frame('planning-design',15,-6,44,32,9.8,C.steel,{ghost:true});
 // Expansion foundations and future steel frame in the same campus.
 box('expansion',31.5,.07,26,25,.15,12,C.soil,{expansion:true});for(let x=22;x<=42;x+=5){for(const z of [22,30]){box('expansion',x,.25,z,2.3,.6,2.3,C.concrete,{expansion:true});box('expansion',x,.85,z,.22,4,.22,C.green,{expansion:true})}}for(const z of [22,30])box('expansion',32,4.8,z,21,.24,.24,C.green,{expansion:true});for(let x=23;x<42;x+=6)route('expansion',[[x,-.1,23],[x,-.1,29]],.32,C.green,{expansion:true});
 // Excavator, material laydown and inspection hold point details.
 const vehicle=(scope,x,z)=>{box(scope,x,.2,z,2,.4,3.2,C.black);box(scope,x,.7,z,2.2,.55,2.5,C.orange);box(scope,x+.35,1.25,z-.4,1.2,1.4,1.25,C.orange);box(scope,x+.35,1.75,z+.24,.9,.6,.05,C.glass);route(scope,[[x-.7,1.3,z+.8],[x-.7,3.3,z+2],[x-.7,2.2,z+4]],.20,C.orange);box(scope,x-.7,.5,z+4,.8,.5,1,C.black)};
 vehicle('earthworks',-6,20);vehicle('expansion',40,25);for(let k=0;k<5;k++)pipe('expansion',[20+k*.85,.5,32],[20+k*.85,.5,34],.35,C.concrete,{expansion:true});
 // A testing workstation is an illustrative package-test context, not full IST.
 box('hv-testing',-31,.4,12,2,1.25,1.3,C.green,{build:3});box('hv-testing',-31,1.67,12,1.7,.08,1.05,C.metal,{build:3});box('hv-testing',-31,1.75,11.8,1.1,.65,.1,C.black,{build:3});route('hv-testing',[[-31,1,11.4],[-30,.2,10],[-29,.2,9],[-29,3,9]],.05,C.orange,{build:3});
 for(const p of [[-33,10],[-33,14],[-28,10],[-28,14]]){pipe('hv-testing',[p[0],.1,p[1]],[p[0],1.3,p[1]],.05,C.orange,{build:3});box('hv-testing',p[0],.1,p[1],.5,.06,.5,C.orange,{build:3})}
 box('owner-acceptance',7,.12,29,4,2.7,3,C.concrete,{build:3});box('commissioning-support',-18,.15,10,2.2,2.7,2.3,C.metal,{build:3});
 box('maintenance',42,.1,2,6,3.1,6,C.concrete,{build:3});box('maintenance',42,3.25,2,6.3,.15,6.3,C.white,{build:3});box('permit-authority',-9,.1,-24,1.8,.8,1.8,C.concrete,{planning:true});
 // Perimeter landscaping: abstract architectural trees, always neutral.
 for(let i=0;i<30;i++){const x=-56+i*3.9,z=i%2?-36:-39;pipe('context',[x,0,z],[x,1.9,z],.10,'#acb9ac',{tree:true});pipe('context',[x,1.2,z],[x,3.8+(i%3)*.3,z],1.10,'#afbcad',{tree:true,sides:6})}for(let i=0;i<15;i++){const z=-25+i*4;pipe('context',[55,0,z],[55,2,z],.1,'#acb9ac',{tree:true});pipe('context',[55,1.6,z],[55,4,z],1.05,'#b4c0b2',{tree:true,sides:6})}
 return objects;
}
function buildShader(gl,type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh}
const LIGHT=norm([-0.55,1,.48]);
export class CampusScene{
 constructor(canvas,onMode,onSelect){this.canvas=canvas;this.onSelect=onSelect;this.objects=buildCampus();this.camera={...CAMERAS[0],target:[...CAMERAS[0].target]};this.targetCamera={...this.camera};this.chapter=0;this.selected='power';this.orbit={yaw:0,pitch:0,zoom:1};this.reduced=false;this.open=false;this.dirty=true;this.projected=[];this.moved=false;this.width=1000;this.height=600;this.onMode=onMode;this.initRenderer(onMode);this.events();this.resize();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame)}
 initRenderer(onMode){let gl;try{gl=this.canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'low-power'});if(!gl)throw Error('WebGL unavailable');const program=gl.createProgram();gl.attachShader(program,buildShader(gl,gl.VERTEX_SHADER,`attribute vec3 a_position;attribute vec3 a_normal;uniform mat4 u_matrix;varying vec3 v_normal;varying vec3 v_pos;void main(){v_normal=a_normal;v_pos=a_position;gl_Position=u_matrix*vec4(a_position,1.0);}`));gl.attachShader(program,buildShader(gl,gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 v_normal;varying vec3 v_pos;uniform vec3 u_color;uniform float u_alpha;void main(){float sun=max(0.0,dot(normalize(v_normal),normalize(vec3(-.55,1.,.48))));float bounce=max(0.0,dot(normalize(v_normal),normalize(vec3(.8,.25,-.5))));float ambient=.68+sun*.30+bounce*.08;vec3 c=u_color*ambient;gl_FragColor=vec4(c,u_alpha);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('WebGL shader link failed');this.gl=gl;this.program=program;gl.useProgram(program);this.aPos=gl.getAttribLocation(program,'a_position');this.aNormal=gl.getAttribLocation(program,'a_normal');this.uMatrix=gl.getUniformLocation(program,'u_matrix');this.uColor=gl.getUniformLocation(program,'u_color');this.uAlpha=gl.getUniformLocation(program,'u_alpha');for(const o of this.objects){const pts=[],normals=[];for(const f of o.faces)for(let k=1;k<f.pts.length-1;k++)for(const v of [f.pts[0],f.pts[k],f.pts[k+1]]){pts.push(...v);normals.push(...f.normal)}o.count=pts.length/3;o.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,o.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pts),gl.STATIC_DRAW);o.nbuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,o.nbuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(normals),gl.STATIC_DRAW)}gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.mode='webgl';onMode('WebGL · 3D campus')}catch(e){if(gl){const replacement=document.createElement('canvas');replacement.id=this.canvas.id;replacement.tabIndex=0;replacement.setAttribute('aria-label',this.canvas.getAttribute('aria-label'));this.canvas.replaceWith(replacement);this.canvas=replacement}this.ctx=this.canvas.getContext('2d',{alpha:false});this.mode='canvas';onMode('Canvas · simplified 3D')}}
 events(){let down=null;this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,yaw:this.orbit.yaw,pitch:this.orbit.pitch};this.moved=false;if(e.pointerType!=='touch')this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(e.pointerType==='touch'&&Math.abs(dy)>Math.abs(dx)*1.25)return;if(Math.abs(dx)+Math.abs(dy)>6)this.moved=true;if(this.moved){this.orbit.yaw=down.yaw+dx*.004;this.orbit.pitch=Math.max(-.23,Math.min(.35,down.pitch+dy*.003));this.dirty=true}});const release=e=>{if(down&&!this.moved){const rect=this.canvas.getBoundingClientRect();this.pick(e.clientX-rect.left,e.clientY-rect.top)}down=null};this.canvas.addEventListener('pointerup',release);this.canvas.addEventListener('pointercancel',()=>down=null);this.canvas.addEventListener('lostpointercapture',()=>down=null);this.canvas.addEventListener('keydown',e=>{let used=true;if(e.key==='ArrowLeft')this.orbit.yaw-=.09;else if(e.key==='ArrowRight')this.orbit.yaw+=.09;else if(e.key==='ArrowUp')this.orbit.pitch=Math.min(.35,this.orbit.pitch+.06);else if(e.key==='ArrowDown')this.orbit.pitch=Math.max(-.23,this.orbit.pitch-.06);else if(e.key==='+'||e.key==='=')this.orbit.zoom=Math.max(.65,this.orbit.zoom-.08);else if(e.key==='-')this.orbit.zoom=Math.min(1.4,this.orbit.zoom+.08);else if(e.key==='0')this.reset();else used=false;if(used){e.preventDefault();this.dirty=true}});new ResizeObserver(()=>this.resize()).observe(this.canvas.parentElement);this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();const old=this.canvas,replacement=document.createElement('canvas');replacement.id=old.id;replacement.tabIndex=0;replacement.setAttribute('aria-label',old.getAttribute('aria-label'));old.replaceWith(replacement);this.canvas=replacement;this.gl=null;this.ctx=replacement.getContext('2d',{alpha:false});this.mode='canvas';this.onMode('Canvas · simplified 3D');this.events();this.resize();this.dirty=true})}
 resize(){const rect=this.canvas.parentElement.getBoundingClientRect();this.width=Math.max(1,rect.width);this.height=Math.max(1,rect.height);this.dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(this.width*this.dpr);this.canvas.height=Math.round(this.height*this.dpr);this.dirty=true}
 setState(chapter,selected,open){this.chapter=chapter;this.selected=selected;this.open=open;this.targetCamera={...CAMERAS[chapter],target:[...CAMERAS[chapter].target]};this.dirty=true}
 reset(){this.orbit={yaw:0,pitch:0,zoom:1};this.dirty=true}
 basis(){const yaw=this.camera.yaw+this.orbit.yaw,pitch=this.camera.pitch+this.orbit.pitch;this.right=[Math.cos(yaw),0,-Math.sin(yaw)];this.up=[-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)];this.forward=[Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)];const mobile=this.width<761&&this.height>this.width*.5;this.scale=Math.min(this.width/(this.camera.span*(mobile?.96:1)),this.height/(this.camera.span*(mobile?.49:.62)))/this.orbit.zoom;this.cx=this.width*(mobile?.51:this.open?.48:.61);this.cy=this.height*(mobile?.54:.57);this.renderTarget=this.camera.target}
 project(p){const a=sub(p,this.renderTarget);return{x:this.cx+dot(a,this.right)*this.scale,y:this.cy-dot(a,this.up)*this.scale,z:dot(a,this.forward)}}
 style(o){let visible=true,opacity=1;const c=this.chapter;const active=this.isActive(o);if(o.shadow)return{visible:true,color:[.68,.72,.69],opacity:o.opacity};if(o.terrain&&c===2&&o.color[0]<.85){}if(o.trench){visible=c!==2&&c!==4;opacity=.7}if(o.build>=3&&c===1)visible=active;if(o.build>=3&&c===2)visible=active||o.scope==='structure-enclosure'&&!o.roof&&!o.cut;if(o.roof||o.cut)visible=[0,6].includes(c)||o.roof&&this.selected==='hvac';if(o.trenchWall&&[2,4].includes(c))visible=false;if(o.hvac&&[2,3,4,5].includes(c)&&this.selected!=='hvac')visible=false;if(o.planning)visible=c===1||this.selected==='planning-design';if(o.ghost)visible=c===1;if(o.expansion)visible=c===0||c===6||this.selected==='expansion';if(o.tree&&this.width<761){}if(o.fence){opacity=.16}
 let color=active?o.color:o.terrain?[.94,.945,.945]:o.flat?[.84,.85,.85]:o.tree?[.75,.77,.77]:[.80,.82,.82];if(o.ghost){color=[.68,.71,.71];opacity=.55}if(o.scope==='context'&&!o.shadow&&!o.terrain&&!o.flat&&!o.tree)color=[.81,.83,.83];return{visible,color,opacity};}
 isActive(o){if(this.selected==='power')return['generation','powerlines','substations'].includes(o.scope);if(this.selected==='interface')return['utilities','electrical'].includes(o.scope);if(this.selected==='hv-testing')return o.scope==='hv-testing'||o.scope==='substations'&&Math.hypot(o.center[0]+28,o.center[2]-9)<4.5;return o.scope===this.selected}
 frame(){if(document.hidden){requestAnimationFrame(this.frame);return}let moving=false;const lerp=(a,b)=>a+(b-a)*(this.reduced?1:.095);for(const k of ['yaw','pitch','span']){if(Math.abs(this.camera[k]-this.targetCamera[k])>.001){this.camera[k]=lerp(this.camera[k],this.targetCamera[k]);moving=true}}this.camera.target=this.camera.target.map((v,i)=>{const next=lerp(v,this.targetCamera.target[i]);if(Math.abs(next-v)>.001)moving=true;return next});if(this.dirty||moving){this.basis();this.mode==='webgl'?this.drawGL():this.drawCanvas();this.drawLabels?.();this.dirty=false}requestAnimationFrame(this.frame)}
 drawGL(){const g=this.gl;g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(.975,.98,.98,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);const sx=2*this.scale/this.width,sy=2*this.scale/this.height,depth=.003;const r=this.right,u=this.up,f=this.forward,t=this.renderTarget;const m=new Float32Array([r[0]*sx,u[0]*sy,-f[0]*depth,0,r[1]*sx,u[1]*sy,-f[1]*depth,0,r[2]*sx,u[2]*sy,-f[2]*depth,0,2*this.cx/this.width-1-dot(t,r)*sx,1-2*this.cy/this.height-dot(t,u)*sy,dot(t,f)*depth,1]);g.uniformMatrix4fv(this.uMatrix,false,m);g.enableVertexAttribArray(this.aPos);g.enableVertexAttribArray(this.aNormal);for(const o of this.objects){const s=this.style(o);if(!s.visible)continue;g.uniform3fv(this.uColor,s.color);g.uniform1f(this.uAlpha,s.opacity);g.bindBuffer(g.ARRAY_BUFFER,o.buffer);g.vertexAttribPointer(this.aPos,3,g.FLOAT,false,0,0);g.bindBuffer(g.ARRAY_BUFFER,o.nbuffer);g.vertexAttribPointer(this.aNormal,3,g.FLOAT,false,0,0);g.depthMask(s.opacity>.95);g.drawArrays(g.TRIANGLES,0,o.count)}g.depthMask(true)}
 drawCanvas(){const c=this.ctx,w=this.width,h=this.height;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.fillStyle='#f8faf9';c.fillRect(0,0,w,h);const faces=[];for(const o of this.objects){const s=this.style(o);if(!s.visible)continue;for(const f of o.faces){if(dot(f.normal,this.forward)<-.02)continue;const pts=f.pts.map(p=>this.project(p));if(pts.every(p=>p.x<-20)||pts.every(p=>p.x>w+20)||pts.every(p=>p.y<-20)||pts.every(p=>p.y>h+20))continue;const depth=pts.reduce((n,p)=>n+p.z,0)/pts.length;const light=.69+Math.max(0,dot(f.normal,LIGHT))*.27;const color=s.color.map(v=>Math.round(Math.min(1,v*light)*255));faces.push({pts,depth,color,opacity:s.opacity,base:o.terrain?0:o.flat||o.shadow?1:2,flat:o.flat||o.shadow||o.terrain,active:this.isActive(o)})}}faces.sort((a,b)=>a.base-b.base||a.depth-b.depth);for(const f of faces){c.beginPath();c.moveTo(f.pts[0].x,f.pts[0].y);for(let k=1;k<f.pts.length;k++)c.lineTo(f.pts[k].x,f.pts[k].y);c.closePath();c.globalAlpha=f.opacity;c.fillStyle=`rgb(${f.color.join(',')})`;c.fill();if(!f.flat){c.strokeStyle=f.active?'rgba(21,66,40,.16)':'rgba(76,99,80,.12)';c.lineWidth=.45;c.stroke()}}c.globalAlpha=1}
 pick(x,y){let closest=null;for(const [id,p]of Object.entries(ANCHORS)){if(!this.selectable?.includes(id))continue;const q=this.project(p),d=Math.hypot(q.x-x,q.y-y);if(d<48&&(!closest||d<closest.d))closest={id,d}}if(closest)this.onSelect(closest.id)}
}
